"""make application fields nullable

Revision ID: 6f457c746bb2
Revises: 21d6bfdb24c2
Create Date: 2026-05-26 16:18:08.350525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f457c746bb2'
down_revision: Union[str, Sequence[str], None] = '21d6bfdb24c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'visa_type_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('applications', 'applicant_nationality',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'applicant_nationality',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('applications', 'visa_type_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
