"""initial_migration

Revision ID: 84d2af6f4e72
Revises: 
Create Date: 2026-05-25 12:12:37.865863

"""
from typing import Sequence, Union
import uuid
import json

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84d2af6f4e72'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destination_countries',
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('flag_emoji', sa.String(length=10), nullable=True),
    sa.Column('processing_time_days', sa.Integer(), nullable=True),
    sa.Column('visa_fee_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('embassy_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('country_code')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', 'reviewer', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('visa_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('purpose', sa.Enum('tourist', 'business', 'student', 'family', 'transit', name='visa_purpose'), nullable=False),
    sa.Column('visa_name', sa.String(length=200), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('max_stay_days', sa.Integer(), nullable=True),
    sa.Column('is_multiple_entry', sa.Boolean(), nullable=False),
    sa.Column('fee_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('processing_time_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['destination_countries.country_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('visa_type_id', sa.Uuid(), nullable=False),
    sa.Column('applicant_nationality', sa.String(length=3), nullable=False),
    sa.Column('step', sa.Enum('country_selection', 'visa_type_selection', 'passport_upload', 'form_filling', 'document_upload', 'face_verification', 'completed', name='application_step'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'under_review', 'approved', 'rejected', 'manual_review', name='application_status'), nullable=False),
    sa.Column('form_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('face_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('passport_mrz_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visa_type_id'], ['visa_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_index(op.f('ix_applications_visa_type_id'), 'applications', ['visa_type_id'], unique=False)
    op.create_table('form_field_config',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('visa_type_id', sa.Uuid(), nullable=False),
    sa.Column('applicant_nationality', sa.String(length=3), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_label', sa.String(length=200), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_regex', sa.Text(), nullable=True),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['visa_type_id'], ['visa_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visa_type_id', 'applicant_nationality', 'field_name', name='unique_visa_field')
    )
    op.create_index(op.f('ix_form_field_config_visa_type_id'), 'form_field_config', ['visa_type_id'], unique=False)
    op.create_table('visa_requirements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('visa_type_id', sa.Uuid(), nullable=False),
    sa.Column('applicant_nationality', sa.String(length=3), nullable=False),
    sa.Column('document_type', sa.Enum('passport', 'bank_statement', 'flight_ticket', 'hotel_booking', 'travel_insurance', 'employment_letter', 'national_id', 'photograph', 'visa_form', 'other', name='document_type'), nullable=False),
    sa.Column('document_label', sa.String(length=255), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('max_age_days', sa.Integer(), nullable=True),
    sa.Column('min_validity_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['visa_type_id'], ['visa_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visa_requirements_applicant_nationality'), 'visa_requirements', ['applicant_nationality'], unique=False)
    op.create_index(op.f('ix_visa_requirements_visa_type_id'), 'visa_requirements', ['visa_type_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_application_id'), 'audit_logs', ['application_id'], unique=False)
    op.create_table('uploaded_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.Enum('passport', 'bank_statement', 'flight_ticket', 'hotel_booking', 'travel_insurance', 'employment_letter', 'national_id', 'photograph', 'visa_form', 'other', name='document_type'), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size_kb', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('pending', 'valid', 'invalid', 'expired', name='document_status'), nullable=False),
    sa.Column('ocr_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_bank_statement', sa.Boolean(), nullable=False),
    sa.Column('bank_statement_from_date', sa.Date(), nullable=True),
    sa.Column('bank_statement_to_date', sa.Date(), nullable=True),
    sa.Column('bank_statement_min_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_documents_application_id'), 'uploaded_documents', ['application_id'], unique=False)
    op.create_index(op.f('ix_uploaded_documents_document_type'), 'uploaded_documents', ['document_type'], unique=False)
    op.create_table('application_checklists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['uploaded_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requirement_id'], ['visa_requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_checklists_application_id'), 'application_checklists', ['application_id'], unique=False)

    # Seed destination_countries
    op.bulk_insert(
        sa.table('destination_countries',
            sa.column('country_code', sa.String),
            sa.column('country_name', sa.String),
            sa.column('region', sa.String),
            sa.column('flag_emoji', sa.String),
            sa.column('processing_time_days', sa.Integer),
            sa.column('visa_fee_usd', sa.Numeric),
            sa.column('embassy_url', sa.Text),
            sa.column('is_active', sa.Boolean),
            sa.column('notes', sa.Text)
        ),
        [
            {'country_code': 'AE', 'country_name': 'United Arab Emirates', 'region': 'Gulf', 'flag_emoji': '🇦🇪', 'processing_time_days': 14, 'visa_fee_usd': 90.00, 'embassy_url': 'https://www.mofa.gov.ae/', 'is_active': True, 'notes': 'Popular Middle East destination'},
            {'country_code': 'GB', 'country_name': 'United Kingdom', 'region': 'Europe', 'flag_emoji': '🇬🇧', 'processing_time_days': 15, 'visa_fee_usd': 130.00, 'embassy_url': 'https://www.gov.uk/browse/visas-immigration', 'is_active': True, 'notes': 'Standard Visitor Visa processes'},
            {'country_code': 'US', 'country_name': 'United States', 'region': 'Americas', 'flag_emoji': '🇺🇸', 'processing_time_days': 30, 'visa_fee_usd': 185.00, 'embassy_url': 'https://travel.state.gov/', 'is_active': True, 'notes': 'B1/B2 tourist and business visas'},
            {'country_code': 'DE', 'country_name': 'Germany', 'region': 'Schengen', 'flag_emoji': '🇩🇪', 'processing_time_days': 15, 'visa_fee_usd': 90.00, 'embassy_url': 'https://www.auswaertiges-amt.de/', 'is_active': True, 'notes': 'Schengen representative country'},
            {'country_code': 'SG', 'country_name': 'Singapore', 'region': 'Asia', 'flag_emoji': '🇸🇬', 'processing_time_days': 7, 'visa_fee_usd': 30.00, 'embassy_url': 'https://www.ica.gov.sg/', 'is_active': True, 'notes': 'Southeast Asian financial hub'},
            {'country_code': 'IN', 'country_name': 'India', 'region': 'Asia', 'flag_emoji': '🇮🇳', 'processing_time_days': 4, 'visa_fee_usd': 25.00, 'embassy_url': 'https://indianvisaonline.gov.in/', 'is_active': True, 'notes': 'E-visa tourist and business applications'}
        ]
    )

    # Seed visa_types
    op.bulk_insert(
        sa.table('visa_types',
            sa.column('id', sa.Uuid),
            sa.column('country_code', sa.String),
            sa.column('purpose', sa.Enum('tourist', 'business', 'student', 'family', 'transit', name='visa_purpose')),
            sa.column('visa_name', sa.String),
            sa.column('duration_days', sa.Integer),
            sa.column('max_stay_days', sa.Integer),
            sa.column('is_multiple_entry', sa.Boolean),
            sa.column('fee_usd', sa.Numeric),
            sa.column('processing_time_days', sa.Integer),
            sa.column('is_active', sa.Boolean)
        ),
        [
            {'id': uuid.UUID('a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d'), 'country_code': 'AE', 'purpose': 'tourist', 'visa_name': 'UAE Tourist Visa', 'duration_days': 30, 'max_stay_days': 30, 'is_multiple_entry': False, 'fee_usd': 90.00, 'processing_time_days': 14, 'is_active': True},
            {'id': uuid.UUID('b2c3d4e5-f67a-8b9c-0d1e-2f3a4b5c6d7e'), 'country_code': 'AE', 'purpose': 'transit', 'visa_name': 'UAE Transit Visa', 'duration_days': 4, 'max_stay_days': 4, 'is_multiple_entry': False, 'fee_usd': 30.00, 'processing_time_days': 4, 'is_active': True},
            {'id': uuid.UUID('c3d4e5f6-7a8b-9c0d-1e2f-3a4b5c6d7e8f'), 'country_code': 'GB', 'purpose': 'tourist', 'visa_name': 'UK Standard Visitor Visa', 'duration_days': 180, 'max_stay_days': 180, 'is_multiple_entry': True, 'fee_usd': 130.00, 'processing_time_days': 15, 'is_active': True},
            {'id': uuid.UUID('d4e5f67a-8b9c-0d1e-2f3a-4b5c6d7e8f9a'), 'country_code': 'GB', 'purpose': 'business', 'visa_name': 'UK Business Visitor Visa', 'duration_days': 180, 'max_stay_days': 180, 'is_multiple_entry': True, 'fee_usd': 130.00, 'processing_time_days': 15, 'is_active': True},
            {'id': uuid.UUID('e5f67a8b-9c0d-1e2f-3a4b-5c6d7e8f9a0b'), 'country_code': 'GB', 'purpose': 'student', 'visa_name': 'UK Student Visa', 'duration_days': 365, 'max_stay_days': 365, 'is_multiple_entry': False, 'fee_usd': 490.00, 'processing_time_days': 20, 'is_active': True},
            {'id': uuid.UUID('f67a8b9c-0d1e-2f3a-4b5c-6d7e8f9a0b1c'), 'country_code': 'US', 'purpose': 'tourist', 'visa_name': 'US B1/B2 Tourist Visa', 'duration_days': 180, 'max_stay_days': 180, 'is_multiple_entry': True, 'fee_usd': 185.00, 'processing_time_days': 30, 'is_active': True},
            {'id': uuid.UUID('7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d'), 'country_code': 'US', 'purpose': 'business', 'visa_name': 'US B1/B2 Business Visa', 'duration_days': 180, 'max_stay_days': 180, 'is_multiple_entry': True, 'fee_usd': 185.00, 'processing_time_days': 30, 'is_active': True},
            {'id': uuid.UUID('8b9c0d1e-2f3a-4b5c-6d7e-8f9a0b1c2d3e'), 'country_code': 'DE', 'purpose': 'tourist', 'visa_name': 'Schengen Tourist Visa', 'duration_days': 90, 'max_stay_days': 90, 'is_multiple_entry': True, 'fee_usd': 90.00, 'processing_time_days': 15, 'is_active': True},
            {'id': uuid.UUID('9c0d1e2f-3a4b-5c6d-7e8f-9a0b1c2d3e4f'), 'country_code': 'DE', 'purpose': 'business', 'visa_name': 'Schengen Business Visa', 'duration_days': 90, 'max_stay_days': 90, 'is_multiple_entry': True, 'fee_usd': 90.00, 'processing_time_days': 15, 'is_active': True},
            {'id': uuid.UUID('0d1e2f3a-4b5c-6d7e-8f9a-0b1c2d3e4f5a'), 'country_code': 'SG', 'purpose': 'tourist', 'visa_name': 'Singapore Tourist Visa', 'duration_days': 30, 'max_stay_days': 30, 'is_multiple_entry': False, 'fee_usd': 30.00, 'processing_time_days': 7, 'is_active': True},
            {'id': uuid.UUID('1e2f3a4b-5c6d-7e8f-9a0b-1c2d3e4f5a6b'), 'country_code': 'IN', 'purpose': 'tourist', 'visa_name': 'India e-Visa Tourist', 'duration_days': 30, 'max_stay_days': 30, 'is_multiple_entry': False, 'fee_usd': 25.00, 'processing_time_days': 4, 'is_active': True},
            {'id': uuid.UUID('2f3a4b5c-6d7e-8f9a-0b1c-2d3e4f5a6b7c'), 'country_code': 'IN', 'purpose': 'business', 'visa_name': 'India e-Visa Business', 'duration_days': 365, 'max_stay_days': 180, 'is_multiple_entry': True, 'fee_usd': 80.00, 'processing_time_days': 4, 'is_active': True}
        ]
    )

    # Seed visa_requirements
    op.bulk_insert(
        sa.table('visa_requirements',
            sa.column('id', sa.Uuid),
            sa.column('visa_type_id', sa.Uuid),
            sa.column('applicant_nationality', sa.String),
            sa.column('document_type', sa.Enum('passport', 'bank_statement', 'flight_ticket', 'hotel_booking', 'travel_insurance', 'employment_letter', 'national_id', 'photograph', 'visa_form', 'other', name='document_type')),
            sa.column('document_label', sa.String),
            sa.column('is_mandatory', sa.Boolean),
            sa.column('max_age_days', sa.Integer),
            sa.column('min_validity_days', sa.Integer),
            sa.column('notes', sa.Text),
            sa.column('display_order', sa.Integer)
        ),
        [
            # AE tourist
            {'id': uuid.UUID('10000000-0000-0000-0000-000000000001'), 'visa_type_id': uuid.UUID('a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d'), 'applicant_nationality': 'ALL', 'document_type': 'passport', 'document_label': 'Original Passport', 'is_mandatory': True, 'max_age_days': None, 'min_validity_days': 180, 'notes': 'Must be valid for at least 180 days from arrival', 'display_order': 10},
            {'id': uuid.UUID('10000000-0000-0000-0000-000000000002'), 'visa_type_id': uuid.UUID('a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d'), 'applicant_nationality': 'ALL', 'document_type': 'photograph', 'document_label': 'Recent Photograph', 'is_mandatory': True, 'max_age_days': None, 'min_validity_days': None, 'notes': 'White background, passport size', 'display_order': 20},
            {'id': uuid.UUID('10000000-0000-0000-0000-000000000003'), 'visa_type_id': uuid.UUID('a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d'), 'applicant_nationality': 'ALL', 'document_type': 'flight_ticket', 'document_label': 'Return Flight Ticket', 'is_mandatory': True, 'max_age_days': None, 'min_validity_days': None, 'notes': 'Confirmed round trip booking', 'display_order': 30},
            {'id': uuid.UUID('10000000-0000-0000-0000-000000000004'), 'visa_type_id': uuid.UUID('a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d'), 'applicant_nationality': 'ALL', 'document_type': 'hotel_booking', 'document_label': 'Hotel Booking Confirmation', 'is_mandatory': True, 'max_age_days': None, 'min_validity_days': None, 'notes': 'Proof of accommodation for the entire stay', 'display_order': 40},
            {'id': uuid.UUID('10000000-0000-0000-0000-000000000005'), 'visa_type_id': uuid.UUID('a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d'), 'applicant_nationality': 'ALL', 'document_type': 'bank_statement', 'document_label': 'Recent Bank Statement', 'is_mandatory': True, 'max_age_days': 90, 'min_validity_days': None, 'notes': 'Last 6 months, minimum AED 3,000 balance', 'display_order': 50},
            {'id': uuid.UUID('10000000-0000-0000-0000-000000000006'), 'visa_type_id': uuid.UUID('a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d'), 'applicant_nationality': 'ALL', 'document_type': 'travel_insurance', 'document_label': 'Travel Insurance', 'is_mandatory': True, 'max_age_days': None, 'min_validity_days': None, 'notes': 'Medical cover valid in the UAE', 'display_order': 60},
            {'id': uuid.UUID('10000000-0000-0000-0000-000000000007'), 'visa_type_id': uuid.UUID('a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d'), 'applicant_nationality': 'IN', 'document_type': 'national_id', 'document_label': 'Aadhaar Card', 'is_mandatory': True, 'max_age_days': None, 'min_validity_days': None, 'notes': 'Clear front and back copy of Aadhaar Card', 'display_order': 70},
            # GB tourist
            {'id': uuid.UUID('20000000-0000-0000-0000-000000000001'), 'visa_type_id': uuid.UUID('c3d4e5f6-7a8b-9c0d-1e2f-3a4b5c6d7e8f'), 'applicant_nationality': 'ALL', 'document_type': 'passport', 'document_label': 'Current Passport', 'is_mandatory': True, 'max_age_days': None, 'min_validity_days': 180, 'notes': 'Must have at least 180 days validity remaining', 'display_order': 10},
            {'id': uuid.UUID('20000000-0000-0000-0000-000000000002'), 'visa_type_id': uuid.UUID('c3d4e5f6-7a8b-9c0d-1e2f-3a4b5c6d7e8f'), 'applicant_nationality': 'ALL', 'document_type': 'photograph', 'document_label': 'Passport Photo', 'is_mandatory': True, 'max_age_days': None, 'min_validity_days': None, 'notes': 'Color photograph matching UK standards', 'display_order': 20},
            {'id': uuid.UUID('20000000-0000-0000-0000-000000000003'), 'visa_type_id': uuid.UUID('c3d4e5f6-7a8b-9c0d-1e2f-3a4b5c6d7e8f'), 'applicant_nationality': 'ALL', 'document_type': 'bank_statement', 'document_label': 'Bank Statements', 'is_mandatory': True, 'max_age_days': 180, 'min_validity_days': None, 'notes': 'Last 6 months statements, must be in English', 'display_order': 30},
            {'id': uuid.UUID('20000000-0000-0000-0000-000000000004'), 'visa_type_id': uuid.UUID('c3d4e5f6-7a8b-9c0d-1e2f-3a4b5c6d7e8f'), 'applicant_nationality': 'ALL', 'document_type': 'employment_letter', 'document_label': 'Employment Letter', 'is_mandatory': True, 'max_age_days': None, 'min_validity_days': None, 'notes': 'No Objection Certificate from current employer', 'display_order': 40},
            {'id': uuid.UUID('20000000-0000-0000-0000-000000000005'), 'visa_type_id': uuid.UUID('c3d4e5f6-7a8b-9c0d-1e2f-3a4b5c6d7e8f'), 'applicant_nationality': 'ALL', 'document_type': 'flight_ticket', 'document_label': 'Flight Booking Reservation', 'is_mandatory': True, 'max_age_days': None, 'min_validity_days': None, 'notes': 'Proposed flight itinerary', 'display_order': 50},
            {'id': uuid.UUID('20000000-0000-0000-0000-000000000006'), 'visa_type_id': uuid.UUID('c3d4e5f6-7a8b-9c0d-1e2f-3a4b5c6d7e8f'), 'applicant_nationality': 'ALL', 'document_type': 'hotel_booking', 'document_label': 'Hotel Accommodation Proof', 'is_mandatory': True, 'max_age_days': None, 'min_validity_days': None, 'notes': 'Details of stay in the UK', 'display_order': 60},
            {'id': uuid.UUID('20000000-0000-0000-0000-000000000007'), 'visa_type_id': uuid.UUID('c3d4e5f6-7a8b-9c0d-1e2f-3a4b5c6d7e8f'), 'applicant_nationality': 'ALL', 'document_type': 'travel_insurance', 'document_label': 'Travel Insurance Certificate', 'is_mandatory': True, 'max_age_days': None, 'min_validity_days': None, 'notes': 'Comprehensive medical and travel coverage', 'display_order': 70},
            # DE tourist
            {'id': uuid.UUID('30000000-0000-0000-0000-000000000001'), 'visa_type_id': uuid.UUID('8b9c0d1e-2f3a-4b5c-6d7e-8f9a0b1c2d3e'), 'applicant_nationality': 'ALL', 'document_type': 'passport', 'document_label': 'National Passport', 'is_mandatory': True, 'max_age_days': None, 'min_validity_days': 90, 'notes': 'Must be valid for 90 days after departure from Schengen area', 'display_order': 10},
            {'id': uuid.UUID('30000000-0000-0000-0000-000000000002'), 'visa_type_id': uuid.UUID('8b9c0d1e-2f3a-4b5c-6d7e-8f9a0b1c2d3e'), 'applicant_nationality': 'ALL', 'document_type': 'photograph', 'document_label': 'Schengen-compliant Photo', 'is_mandatory': True, 'max_age_days': None, 'min_validity_days': None, 'notes': 'Not older than 6 months', 'display_order': 20},
            {'id': uuid.UUID('30000000-0000-0000-0000-000000000003'), 'visa_type_id': uuid.UUID('8b9c0d1e-2f3a-4b5c-6d7e-8f9a0b1c2d3e'), 'applicant_nationality': 'ALL', 'document_type': 'bank_statement', 'document_label': 'Personal Bank Statement', 'is_mandatory': True, 'max_age_days': 90, 'min_validity_days': None, 'notes': 'Prove financial stability for trip duration', 'display_order': 30},
            {'id': uuid.UUID('30000000-0000-0000-0000-000000000004'), 'visa_type_id': uuid.UUID('8b9c0d1e-2f3a-4b5c-6d7e-8f9a0b1c2d3e'), 'applicant_nationality': 'ALL', 'document_type': 'flight_ticket', 'document_label': 'Round-trip Flight Reservation', 'is_mandatory': True, 'max_age_days': None, 'min_validity_days': None, 'notes': 'Flight details with dates and flight numbers', 'display_order': 40},
            {'id': uuid.UUID('30000000-0000-0000-0000-000000000005'), 'visa_type_id': uuid.UUID('8b9c0d1e-2f3a-4b5c-6d7e-8f9a0b1c2d3e'), 'applicant_nationality': 'ALL', 'document_type': 'hotel_booking', 'document_label': 'Proof of Accommodation', 'is_mandatory': True, 'max_age_days': None, 'min_validity_days': None, 'notes': 'Hotel reservation or invitation letter', 'display_order': 50},
            {'id': uuid.UUID('30000000-0000-0000-0000-000000000006'), 'visa_type_id': uuid.UUID('8b9c0d1e-2f3a-4b5c-6d7e-8f9a0b1c2d3e'), 'applicant_nationality': 'ALL', 'document_type': 'travel_insurance', 'document_label': 'Travel Health Insurance', 'is_mandatory': True, 'max_age_days': None, 'min_validity_days': None, 'notes': 'Minimum €30,000 coverage, valid all Schengen states', 'display_order': 60},
            {'id': uuid.UUID('30000000-0000-0000-0000-000000000007'), 'visa_type_id': uuid.UUID('8b9c0d1e-2f3a-4b5c-6d7e-8f9a0b1c2d3e'), 'applicant_nationality': 'ALL', 'document_type': 'employment_letter', 'document_label': 'Certificate of Employment', 'is_mandatory': True, 'max_age_days': None, 'min_validity_days': None, 'notes': 'Position, salary, and approved leave details', 'display_order': 70},
            # US tourist
            {'id': uuid.UUID('40000000-0000-0000-0000-000000000001'), 'visa_type_id': uuid.UUID('f67a8b9c-0d1e-2f3a-4b5c-6d7e8f9a0b1c'), 'applicant_nationality': 'ALL', 'document_type': 'passport', 'document_label': 'Valid Passport', 'is_mandatory': True, 'max_age_days': None, 'min_validity_days': 180, 'notes': 'Must be valid for at least 180 days', 'display_order': 10},
            {'id': uuid.UUID('40000000-0000-0000-0000-000000000002'), 'visa_type_id': uuid.UUID('f67a8b9c-0d1e-2f3a-4b5c-6d7e8f9a0b1c'), 'applicant_nationality': 'ALL', 'document_type': 'photograph', 'document_label': 'US Visa Photo', 'is_mandatory': True, 'max_age_days': None, 'min_validity_days': None, 'notes': '2x2 inches, white background, digital file', 'display_order': 20},
            {'id': uuid.UUID('40000000-0000-0000-0000-000000000003'), 'visa_type_id': uuid.UUID('f67a8b9c-0d1e-2f3a-4b5c-6d7e8f9a0b1c'), 'applicant_nationality': 'ALL', 'document_type': 'bank_statement', 'document_label': 'Financial Documents', 'is_mandatory': True, 'max_age_days': 90, 'min_validity_days': None, 'notes': 'Prove sufficient funds for stay', 'display_order': 30},
            {'id': uuid.UUID('40000000-0000-0000-0000-000000000004'), 'visa_type_id': uuid.UUID('f67a8b9c-0d1e-2f3a-4b5c-6d7e8f9a0b1c'), 'applicant_nationality': 'ALL', 'document_type': 'employment_letter', 'document_label': 'Employment Verification Letter', 'is_mandatory': True, 'max_age_days': None, 'min_validity_days': None, 'notes': 'Letter confirming job title, salary, and employment length', 'display_order': 40},
            {'id': uuid.UUID('40000000-0000-0000-0000-000000000005'), 'visa_type_id': uuid.UUID('f67a8b9c-0d1e-2f3a-4b5c-6d7e8f9a0b1c'), 'applicant_nationality': 'ALL', 'document_type': 'visa_form', 'document_label': 'DS-160 Confirmation Page', 'is_mandatory': True, 'max_age_days': None, 'min_validity_days': None, 'notes': 'DS-160 form confirmation page barcode', 'display_order': 50},
            # SG tourist
            {'id': uuid.UUID('50000000-0000-0000-0000-000000000001'), 'visa_type_id': uuid.UUID('0d1e2f3a-4b5c-6d7e-8f9a-0b1c2d3e4f5a'), 'applicant_nationality': 'ALL', 'document_type': 'passport', 'document_label': 'Passport Bio Page', 'is_mandatory': True, 'max_age_days': None, 'min_validity_days': 180, 'notes': 'Must have at least 180 days validity on entry', 'display_order': 10},
            {'id': uuid.UUID('50000000-0000-0000-0000-000000000002'), 'visa_type_id': uuid.UUID('0d1e2f3a-4b5c-6d7e-8f9a-0b1c2d3e4f5a'), 'applicant_nationality': 'ALL', 'document_type': 'photograph', 'document_label': 'Digital Photo', 'is_mandatory': True, 'max_age_days': None, 'min_validity_days': None, 'notes': 'Matt/semi-matt finish, white background', 'display_order': 20},
            {'id': uuid.UUID('50000000-0000-0000-0000-000000000003'), 'visa_type_id': uuid.UUID('0d1e2f3a-4b5c-6d7e-8f9a-0b1c2d3e4f5a'), 'applicant_nationality': 'ALL', 'document_type': 'bank_statement', 'document_label': 'Bank Statements', 'is_mandatory': True, 'max_age_days': 90, 'min_validity_days': None, 'notes': 'Last 3 months bank statements', 'display_order': 30},
            {'id': uuid.UUID('50000000-0000-0000-0000-000000000004'), 'visa_type_id': uuid.UUID('0d1e2f3a-4b5c-6d7e-8f9a-0b1c2d3e4f5a'), 'applicant_nationality': 'ALL', 'document_type': 'flight_ticket', 'document_label': 'Flight Itinerary', 'is_mandatory': True, 'max_age_days': None, 'min_validity_days': None, 'notes': 'Details of flights into and out of Singapore', 'display_order': 40},
            {'id': uuid.UUID('50000000-0000-0000-0000-000000000005'), 'visa_type_id': uuid.UUID('0d1e2f3a-4b5c-6d7e-8f9a-0b1c2d3e4f5a'), 'applicant_nationality': 'ALL', 'document_type': 'hotel_booking', 'document_label': 'Accommodation details', 'is_mandatory': True, 'max_age_days': None, 'min_validity_days': None, 'notes': 'Hotel booking verification', 'display_order': 50},
            # IN tourist
            {'id': uuid.UUID('60000000-0000-0000-0000-000000000001'), 'visa_type_id': uuid.UUID('1e2f3a4b-5c6d-7e8f-9a0b-1c2d3e4f5a6b'), 'applicant_nationality': 'ALL', 'document_type': 'passport', 'document_label': 'Passport Scan', 'is_mandatory': True, 'max_age_days': None, 'min_validity_days': 180, 'notes': 'Bio-page of passport containing personal particulars', 'display_order': 10},
            {'id': uuid.UUID('60000000-0000-0000-0000-000000000002'), 'visa_type_id': uuid.UUID('1e2f3a4b-5c6d-7e8f-9a0b-1c2d3e4f5a6b'), 'applicant_nationality': 'ALL', 'document_type': 'photograph', 'document_label': 'Digital Photograph', 'is_mandatory': True, 'max_age_days': None, 'min_validity_days': None, 'notes': 'Square shape, white background', 'display_order': 20}
        ]
    )

    # Query all visa types to dynamically seed FormFieldConfig
    bind = op.get_bind()
    res = bind.execute(sa.text("SELECT id, country_code FROM visa_types"))
    visa_types = res.all()

    common_fields_data = []
    override_fields_data = []

    for vt in visa_types:
        vt_id = vt[0]
        country_code = vt[1]

        common_fields = [
            ('full_name', 'Full Name', 'text', 10, '[]'),
            ('date_of_birth', 'Date of Birth', 'date', 20, '[]'),
            ('passport_number', 'Passport Number', 'text', 30, '[]'),
            ('passport_expiry', 'Passport Expiry Date', 'date', 40, '[]'),
            ('nationality', 'Nationality', 'dropdown', 50, '[]'),
            ('gender', 'Gender', 'dropdown', 60, '["Male", "Female", "Other"]'),
            ('travel_date', 'Expected Arrival Date', 'date', 70, '[]'),
            ('return_date', 'Expected Return Date', 'date', 80, '[]'),
            ('purpose_of_visit', 'Purpose of Visit', 'text', 90, '[]')
        ]

        for name, label, ftype, order, opt_json in common_fields:
            common_fields_data.append({
                'id': uuid.uuid4(),
                'visa_type_id': vt_id,
                'applicant_nationality': 'ALL',
                'field_name': name,
                'field_label': label,
                'field_type': ftype,
                'is_required': True,
                'options': json.loads(opt_json),
                'validation_regex': None,
                'placeholder': None,
                'help_text': None,
                'display_order': order
            })

        if country_code == 'AE':
            override_fields_data.append({
                'id': uuid.uuid4(),
                'visa_type_id': vt_id,
                'applicant_nationality': 'ALL',
                'field_name': 'visa_duration',
                'field_label': 'Visa Duration',
                'field_type': 'dropdown',
                'is_required': True,
                'options': ["30 days", "60 days", "90 days"],
                'validation_regex': None,
                'placeholder': None,
                'help_text': None,
                'display_order': 100
            })
        elif country_code == 'GB':
            override_fields_data.extend([
                {'id': uuid.uuid4(), 'visa_type_id': vt_id, 'applicant_nationality': 'ALL', 'field_name': 'have_previous_uk_visa', 'field_label': 'Have you had a UK visa before?', 'field_type': 'boolean', 'is_required': True, 'options': [], 'validation_regex': None, 'placeholder': None, 'help_text': None, 'display_order': 100},
                {'id': uuid.uuid4(), 'visa_type_id': vt_id, 'applicant_nationality': 'ALL', 'field_name': 'previous_visa_refusals', 'field_label': 'Any previous UK visa refusals?', 'field_type': 'boolean', 'is_required': True, 'options': [], 'validation_regex': None, 'placeholder': None, 'help_text': None, 'display_order': 110},
                {'id': uuid.uuid4(), 'visa_type_id': vt_id, 'applicant_nationality': 'ALL', 'field_name': 'travel_history', 'field_label': 'Travel History', 'field_type': 'text', 'is_required': True, 'options': [], 'validation_regex': None, 'placeholder': None, 'help_text': 'List countries visited in last 10 years', 'display_order': 120}
            ])
        elif country_code == 'US':
            override_fields_data.extend([
                {'id': uuid.uuid4(), 'visa_type_id': vt_id, 'applicant_nationality': 'ALL', 'field_name': 'ds160_confirmation_number', 'field_label': 'DS-160 Confirmation Number', 'field_type': 'text', 'is_required': True, 'options': [], 'validation_regex': None, 'placeholder': None, 'help_text': 'Complete DS-160 on travel.state.gov first', 'display_order': 100},
                {'id': uuid.uuid4(), 'visa_type_id': vt_id, 'applicant_nationality': 'ALL', 'field_name': 'have_us_visa_before', 'field_label': 'Have you been issued a US visa before?', 'field_type': 'boolean', 'is_required': True, 'options': [], 'validation_regex': None, 'placeholder': None, 'help_text': None, 'display_order': 110},
                {'id': uuid.uuid4(), 'visa_type_id': vt_id, 'applicant_nationality': 'ALL', 'field_name': 'ssn_or_itin', 'field_label': 'SSN or ITIN', 'field_type': 'text', 'is_required': False, 'options': [], 'validation_regex': None, 'placeholder': None, 'help_text': 'If you have one', 'display_order': 120}
            ])
        elif country_code == 'DE':
            schengen_countries = ["Germany", "France", "Italy", "Spain", "Austria", "Belgium", "Czech Republic", "Denmark", "Estonia", "Finland", "Greece", "Hungary", "Iceland", "Latvia", "Liechtenstein", "Lithuania", "Luxembourg", "Malta", "Netherlands", "Norway", "Poland", "Portugal", "Slovakia", "Slovenia", "Sweden", "Switzerland"]
            override_fields_data.extend([
                {'id': uuid.uuid4(), 'visa_type_id': vt_id, 'applicant_nationality': 'ALL', 'field_name': 'main_destination_country', 'field_label': 'Main Destination Country', 'field_type': 'dropdown', 'is_required': True, 'options': schengen_countries, 'validation_regex': None, 'placeholder': None, 'help_text': None, 'display_order': 100},
                {'id': uuid.uuid4(), 'visa_type_id': vt_id, 'applicant_nationality': 'ALL', 'field_name': 'schengen_before', 'field_label': 'Have you had Schengen visa in last 3 years?', 'field_type': 'boolean', 'is_required': True, 'options': [], 'validation_regex': None, 'placeholder': None, 'help_text': None, 'display_order': 110},
                {'id': uuid.uuid4(), 'visa_type_id': vt_id, 'applicant_nationality': 'ALL', 'field_name': 'travel_insurance_provider', 'field_label': 'Travel Insurance Provider', 'field_type': 'text', 'is_required': True, 'options': [], 'validation_regex': None, 'placeholder': None, 'help_text': None, 'display_order': 120}
            ])
        elif country_code == 'IN':
            airports = ["Delhi (DEL)", "Mumbai (BOM)", "Bengaluru (BLR)", "Chennai (MAA)", "Kolkata (CCU)", "Hyderabad (HYD)"]
            override_fields_data.extend([
                {'id': uuid.uuid4(), 'visa_type_id': vt_id, 'applicant_nationality': 'ALL', 'field_name': 'port_of_arrival', 'field_label': 'Port of Arrival', 'field_type': 'dropdown', 'is_required': True, 'options': airports, 'validation_regex': None, 'placeholder': None, 'help_text': None, 'display_order': 100},
                {'id': uuid.uuid4(), 'visa_type_id': vt_id, 'applicant_nationality': 'ALL', 'field_name': 'expected_port_of_exit', 'field_label': 'Expected Port of Exit', 'field_type': 'dropdown', 'is_required': True, 'options': airports, 'validation_regex': None, 'placeholder': None, 'help_text': None, 'display_order': 110}
            ])

    all_configs = common_fields_data + override_fields_data

    op.bulk_insert(
        sa.table('form_field_config',
            sa.column('id', sa.Uuid),
            sa.column('visa_type_id', sa.Uuid),
            sa.column('applicant_nationality', sa.String),
            sa.column('field_name', sa.String),
            sa.column('field_label', sa.String),
            sa.column('field_type', sa.String),
            sa.column('is_required', sa.Boolean),
            sa.column('options', postgresql.JSONB),
            sa.column('validation_regex', sa.Text),
            sa.column('placeholder', sa.Text),
            sa.column('help_text', sa.Text),
            sa.column('display_order', sa.Integer)
        ),
        all_configs
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_checklists_application_id'), table_name='application_checklists')
    op.drop_table('application_checklists')
    op.drop_index(op.f('ix_uploaded_documents_document_type'), table_name='uploaded_documents')
    op.drop_index(op.f('ix_uploaded_documents_application_id'), table_name='uploaded_documents')
    op.drop_table('uploaded_documents')
    op.drop_index(op.f('ix_audit_logs_application_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_visa_requirements_visa_type_id'), table_name='visa_requirements')
    op.drop_index(op.f('ix_visa_requirements_applicant_nationality'), table_name='visa_requirements')
    op.drop_table('visa_requirements')
    op.drop_index(op.f('ix_form_field_config_visa_type_id'), table_name='form_field_config')
    op.drop_table('form_field_config')
    op.drop_index(op.f('ix_applications_visa_type_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_table('applications')
    op.drop_table('visa_types')
    op.drop_table('users')
    op.drop_table('destination_countries')

    # Drop custom PostgreSQL enum types
    op.execute("DROP TYPE IF EXISTS user_role CASCADE;")
    op.execute("DROP TYPE IF EXISTS visa_purpose CASCADE;")
    op.execute("DROP TYPE IF EXISTS application_step CASCADE;")
    op.execute("DROP TYPE IF EXISTS application_status CASCADE;")
    op.execute("DROP TYPE IF EXISTS document_type CASCADE;")
    op.execute("DROP TYPE IF EXISTS document_status CASCADE;")
    # ### end Alembic commands ###
